# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-17 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WiltseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='codename',
            field=models.CharField(max_length=50, verbose_name='\ucf54\ub4dc\uc774\ub984'),
        ),
        migrations.AlterField(
            model_name='code',
            name='codenum',
            field=models.IntegerField(verbose_name='\ucf54\ub4dc\ubc88\ud638'),
        ),
        migrations.AlterField(
            model_name='code',
            name='where',
            field=models.CharField(max_length=50, verbose_name='\ucf54\ub4dc\ubd84\ub958'),
        ),
    ]
