# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-17 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WiltseApp', '0002_auto_20170117_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='codenum',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='num',
        ),
        migrations.AddField(
            model_name='notice',
            name='code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WiltseApp.Code'),
        ),
    ]
