# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-17 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WiltseApp', '0005_auto_20170117_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
