# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-17 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WiltseApp', '0006_auto_20170117_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='num',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='notice',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
