# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-17 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WiltseApp', '0007_auto_20170117_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='codenum',
            field=models.IntegerField(default=1),
        ),
    ]
