# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-18 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WiltseApp', '0009_handbook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='codenum',
            new_name='codeid',
        ),
        migrations.AddField(
            model_name='code',
            name='codenumber',
            field=models.IntegerField(default=1),
        ),
    ]
