# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-18 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WiltseApp', '0010_auto_20170118_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='codenumber',
            field=models.IntegerField(default=1, verbose_name='\ucf54\ub4dc \uad6c\ubd84 \ubc88\ud638'),
        ),
    ]
