# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 02:15
from __future__ import unicode_literals

import WiltseApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WiltseApp', '0012_auto_20170120_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulation',
            name='num',
            field=models.IntegerField(default=WiltseApp.models.nu),
        ),
    ]
