# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 10:40
from __future__ import unicode_literals

import WiltseApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WiltseApp', '0015_auto_20170124_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='num',
            field=models.IntegerField(default=WiltseApp.models.nu3),
        ),
    ]
