# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WiltseApp', '0016_auto_20170125_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
