# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WiltseApp', '0017_auto_20170131_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
