# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WiltseApp', '0018_auto_20170131_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
